<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Mapify.NET</PackageId>
    <Version>1.2.0</Version>
    <Authors>Benjamin Vettori</Authors>
    <Title>Mapify.NET</Title>
    <Description>A simple mapper library which uses static expressions to map entities in memory or in database with entity framework if combined with LinqKit</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <IncludeSymbols>True</IncludeSymbols>
    <Deterministic>True</Deterministic>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/BenjaminVettori/Mapify.NET</RepositoryUrl>
    <TargetFrameworks>net462;net8.0;net9.0;net10.0;netstandard2.0;netstandard2.1</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="\" />
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
  </ItemGroup>
</Project>
